Fixes XlecX browser
As of v1.9.9 browsing XlecX throws the following error
TypeError: Cannot read property 'getElementsByClassName' of null

This PR removes the getElementById which seems to be causing the issue in xlecx-api.js